import { Plan } from "./types";

export const PLANS: Plan[] = [
  {
    id: "mp-ep",
    workLocation: "Menlo Park",
    allocationArea: "Enterprise Products",
    status: "Live",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-01",
    employeesWithDesks: 51,
    employeesWithoutDesks: 32,
    totalAllocatedSpaces: 272,
    futureHeadcount: 8,
    employeeAssessment: { fullTime: 74, partTime: 3, interns: 4, contingent: 2, other: 0 },
    workspaceAssessment: { assignedDesks: 51, availableDesks: 18, dropIn: 120, reservable: 83 },
    deskPolicy: {
      assignInboundEmbeds: false,
      outboundSeatedWithPillars: true,
      assignPlannedGrowth: true,
      specialArrangementInterns: false,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "mp-fb",
    workLocation: "Menlo Park",
    allocationArea: "Facebook",
    status: "Approved",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-04-28",
    employeesWithDesks: 120,
    employeesWithoutDesks: 45,
    totalAllocatedSpaces: 580,
    futureHeadcount: 15,
    employeeAssessment: { fullTime: 148, partTime: 8, interns: 6, contingent: 3, other: 0 },
    workspaceAssessment: { assignedDesks: 120, availableDesks: 42, dropIn: 280, reservable: 138 },
    deskPolicy: {
      assignInboundEmbeds: true,
      outboundSeatedWithPillars: true,
      assignPlannedGrowth: false,
      specialArrangementInterns: true,
    },
    iptPolicy: {
      minimumWorkDays: 78,
      allowanceNonAssigned: 15,
      allowedStatuses: { drive: true, fly: false, workFromNonMetaBusiness: true, unforeseenCircumstances: true, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "mp-msg",
    workLocation: "Menlo Park",
    allocationArea: "Messenger",
    status: "Submitted",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-10",
    employeesWithDesks: 38,
    employeesWithoutDesks: 22,
    totalAllocatedSpaces: 180,
    futureHeadcount: 5,
    employeeAssessment: { fullTime: 55, partTime: 2, interns: 3, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 38, availableDesks: 12, dropIn: 85, reservable: 45 },
    deskPolicy: {
      assignInboundEmbeds: false,
      outboundSeatedWithPillars: false,
      assignPlannedGrowth: true,
      specialArrangementInterns: false,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: false, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "sf-ig",
    workLocation: "San Francisco",
    allocationArea: "Instagram",
    status: "Policy draft",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-18",
    employeesWithDesks: 67,
    employeesWithoutDesks: 41,
    totalAllocatedSpaces: 340,
    futureHeadcount: 12,
    employeeAssessment: { fullTime: 98, partTime: 5, interns: 5, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 67, availableDesks: 25, dropIn: 160, reservable: 88 },
    deskPolicy: {
      assignInboundEmbeds: null,
      outboundSeatedWithPillars: null,
      assignPlannedGrowth: null,
      specialArrangementInterns: null,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "sf-wa",
    workLocation: "San Francisco",
    allocationArea: "Whatsapp",
    status: "Plan draft",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-20",
    employeesWithDesks: 0,
    employeesWithoutDesks: 0,
    totalAllocatedSpaces: 0,
    futureHeadcount: 0,
    employeeAssessment: { fullTime: 44, partTime: 1, interns: 2, contingent: 1, other: 0 },
    workspaceAssessment: { assignedDesks: 0, availableDesks: 30, dropIn: 70, reservable: 40 },
    deskPolicy: {
      assignInboundEmbeds: null,
      outboundSeatedWithPillars: null,
      assignPlannedGrowth: null,
      specialArrangementInterns: null,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "sv-es",
    workLocation: "Sunnyvale",
    allocationArea: "Enterprise Solution",
    status: "Live",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-01",
    employeesWithDesks: 89,
    employeesWithoutDesks: 21,
    totalAllocatedSpaces: 410,
    futureHeadcount: 10,
    employeeAssessment: { fullTime: 102, partTime: 4, interns: 4, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 89, availableDesks: 31, dropIn: 180, reservable: 110 },
    deskPolicy: {
      assignInboundEmbeds: false,
      outboundSeatedWithPillars: true,
      assignPlannedGrowth: true,
      specialArrangementInterns: false,
    },
    iptPolicy: {
      minimumWorkDays: 78,
      allowanceNonAssigned: 13,
      allowedStatuses: { drive: true, fly: false, workFromNonMetaBusiness: true, unforeseenCircumstances: true, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "sv-ep",
    workLocation: "Sunnyvale",
    allocationArea: "Enterprise Products",
    status: "Submitted",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-14",
    employeesWithDesks: 33,
    employeesWithoutDesks: 17,
    totalAllocatedSpaces: 195,
    futureHeadcount: 6,
    employeeAssessment: { fullTime: 45, partTime: 2, interns: 3, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 33, availableDesks: 14, dropIn: 90, reservable: 58 },
    deskPolicy: {
      assignInboundEmbeds: false,
      outboundSeatedWithPillars: true,
      assignPlannedGrowth: true,
      specialArrangementInterns: false,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "bg-fb",
    workLocation: "Burlingame",
    allocationArea: "Facebook",
    status: "Policy draft",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-16",
    employeesWithDesks: 29,
    employeesWithoutDesks: 18,
    totalAllocatedSpaces: 155,
    futureHeadcount: 4,
    employeeAssessment: { fullTime: 42, partTime: 2, interns: 3, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 29, availableDesks: 10, dropIn: 70, reservable: 46 },
    deskPolicy: {
      assignInboundEmbeds: null,
      outboundSeatedWithPillars: null,
      assignPlannedGrowth: null,
      specialArrangementInterns: null,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "fr-wa",
    workLocation: "Fremont",
    allocationArea: "Whatsapp",
    status: "Approved",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-04-30",
    employeesWithDesks: 18,
    employeesWithoutDesks: 7,
    totalAllocatedSpaces: 90,
    futureHeadcount: 3,
    employeeAssessment: { fullTime: 22, partTime: 1, interns: 2, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 18, availableDesks: 8, dropIn: 40, reservable: 24 },
    deskPolicy: {
      assignInboundEmbeds: true,
      outboundSeatedWithPillars: false,
      assignPlannedGrowth: true,
      specialArrangementInterns: true,
    },
    iptPolicy: {
      minimumWorkDays: 65,
      allowanceNonAssigned: 8,
      allowedStatuses: { drive: true, fly: false, workFromNonMetaBusiness: false, unforeseenCircumstances: true, ptoChoiceSick: true, globalTravelDays: false },
    },
  },
  {
    id: "ny-ig",
    workLocation: "New York",
    allocationArea: "Instagram",
    status: "Live",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-01",
    employeesWithDesks: 74,
    employeesWithoutDesks: 28,
    totalAllocatedSpaces: 395,
    futureHeadcount: 9,
    employeeAssessment: { fullTime: 92, partTime: 5, interns: 5, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 74, availableDesks: 28, dropIn: 175, reservable: 118 },
    deskPolicy: {
      assignInboundEmbeds: false,
      outboundSeatedWithPillars: true,
      assignPlannedGrowth: true,
      specialArrangementInterns: false,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "au-msg",
    workLocation: "Austin",
    allocationArea: "Messenger",
    status: "Plan draft",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-22",
    employeesWithDesks: 0,
    employeesWithoutDesks: 0,
    totalAllocatedSpaces: 0,
    futureHeadcount: 0,
    employeeAssessment: { fullTime: 28, partTime: 0, interns: 1, contingent: 2, other: 0 },
    workspaceAssessment: { assignedDesks: 0, availableDesks: 20, dropIn: 45, reservable: 25 },
    deskPolicy: {
      assignInboundEmbeds: null,
      outboundSeatedWithPillars: null,
      assignPlannedGrowth: null,
      specialArrangementInterns: null,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
  {
    id: "sg-es",
    workLocation: "Singapore",
    allocationArea: "Enterprise Solution",
    status: "Approved",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-04-25",
    employeesWithDesks: 42,
    employeesWithoutDesks: 16,
    totalAllocatedSpaces: 220,
    futureHeadcount: 7,
    employeeAssessment: { fullTime: 52, partTime: 2, interns: 4, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 42, availableDesks: 15, dropIn: 100, reservable: 63 },
    deskPolicy: {
      assignInboundEmbeds: false,
      outboundSeatedWithPillars: true,
      assignPlannedGrowth: true,
      specialArrangementInterns: false,
    },
    iptPolicy: {
      minimumWorkDays: 78,
      allowanceNonAssigned: 12,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: true },
    },
  },
  {
    id: "tk-fb",
    workLocation: "Tokyo",
    allocationArea: "Facebook",
    status: "Policy draft",
    fiscalYear: "FY26",
    quarter: "Q2",
    updatedAt: "2026-05-19",
    employeesWithDesks: 21,
    employeesWithoutDesks: 12,
    totalAllocatedSpaces: 115,
    futureHeadcount: 3,
    employeeAssessment: { fullTime: 30, partTime: 1, interns: 2, contingent: 0, other: 0 },
    workspaceAssessment: { assignedDesks: 21, availableDesks: 9, dropIn: 50, reservable: 35 },
    deskPolicy: {
      assignInboundEmbeds: null,
      outboundSeatedWithPillars: null,
      assignPlannedGrowth: null,
      specialArrangementInterns: null,
    },
    iptPolicy: {
      minimumWorkDays: 91,
      allowanceNonAssigned: 10,
      allowedStatuses: { drive: true, fly: true, workFromNonMetaBusiness: true, unforeseenCircumstances: false, ptoChoiceSick: false, globalTravelDays: false },
    },
  },
];

export function getPlanById(id: string): Plan | undefined {
  return PLANS.find((p) => p.id === id);
}

export function getPlansByLocation() {
  const map = new Map<string, Plan[]>();
  for (const plan of PLANS) {
    const list = map.get(plan.workLocation) ?? [];
    list.push(plan);
    map.set(plan.workLocation, list);
  }
  return map;
}

export function getPlansByAA() {
  const map = new Map<string, Plan[]>();
  for (const plan of PLANS) {
    const list = map.get(plan.allocationArea) ?? [];
    list.push(plan);
    map.set(plan.allocationArea, list);
  }
  return map;
}
